### ISSUE TITLE
Various player bullet patterns

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/Mages#10]

**Comment by Fangor** [comment]
Any suggestions for patterns?

**Comment by MrChro** [comment]
V pattern
firework type patter that shoots one forward and that breaks in a small circle
Are lasers a pattern? 
We have a 3 bullet spread forward, can add a 5 bullet spread.
A circling one, from the original contra if you remember it.  
i'd also have patterns that only fire behind to force people to be forward at times.  Can say the same with side on patterns, since one of our themes is player adaptability.

**Comment by Fangor** [comment]
Yep, lasers are already in.  Exploding shell seems like something we should do.  I also really like more back and side patterns.
